version: '2'
services:

  tkwvalidation:
    container_name: tkwvalidation
    image: damianmurphy/fhir_production_validator:20190301
    ports:
      - 8116:4849
    volumes:
      - /docker-data:/home/service/data
    networks:
      - ccri_net
