version: '2'
services:

  ccrisql:
    container_name: ccrisql
    image: postgres:11.3
    environment:
      - POSTGRES_DB=careconnect
      - POSTGRES_USER=fhirjpa
      - POSTGRES_PASSWORD=fhirjpa
    networks:
      - ccri_net

  ccrifhir:
    container_name: ccrifhir
    image: thorlogic/ccri-fhirserver:latest
    depends_on:
      - ccrisql
    links:
      - ccrisql
    environment:
      - datasource.username=fhirjpa
      - datasource.password=fhirjpa
      - datasource.url=jdbc:postgresql://ccrisql:5432/careconnect
      - datasource.driver=org.postgresql.Driver
      - datasource.path=5432/careconnect
      - datasource.vendor=postgresql
      - datasource.showSql=false
      - datasource.showDdl=false
      - datasource.dialect=org.hibernate.dialect.PostgreSQL9Dialect
      - datasource.ui.serverBase=${FHIR_SERVER_BASE_PROTOCOL}://${FHIR_SERVER_BASE_HOST}/ccri-fhir/STU3
      - datasource.serverBase=${FHIR_SERVER_BASE_PROTOCOL}://${FHIR_SERVER_BASE_HOST}/ccri-fhir/STU3
      - jolokia.username=HSFAdmin
      - jolokia.password=h5fadm!n
      - server.servlet.context-path=/ccri-fhir
      - ccri.software.version=4.0.0
      - ccri.software.name=Care Connect RI FHIR Server
      - ccri.server=Care Connect API (unsecured)
      - ccri.server.base=https://${FHIR_SERVER_BASE_HOST}/ccri-fhir/STU3
      - ccri.guide=https://nhsconnect.github.io/CareConnectAPI/
      - ccri.tkw_server=http://tkwvalidation:4849/$$validate
      - ccri.EPR_resources=AllergyIntolerance,Appointment,Bundle,CarePlan,CareTeam,CodeSystem,ClinicalImpression,ConceptMap,Condition,Consent,DocumentReference,Encounter,Endpoint,EpisodeOfCare,Flag,GraphDefinition,HealthcareService,Immunization,List,Location,Medication,MedicationAdministration,MedicationDispense,MedicationRequest,MedicationStatement,MessageDefinition,NamingSystem,Observation,Organization,Patient,Practitioner,PractitionerRole,Procedure,Questionnaire,QuestionnaireResponse,ReferralRequest,RelatedPerson,Schedule,Slot,StructureDefinition,ValueSet
      - ccri.validate_use_tkw=false
      - ccri.validate_flag=true
    ports:
      - 8105:8186
    extra_hosts:
      # Define an alias to loop back for REST Connections
      - "${FHIR_SERVER_BASE_HOST}:127.0.0.1"
    volumes:
      - gateway-log-volume:/usr/local/tomcat/logs
    networks:
      - ccri_net



  tkwvalidation:
    container_name: tkwvalidation
    image: damianmurphy/fhir_production_validator:20190301
    ports:
      - 8116:4849
    volumes:
      - /docker-data:/home/service/data
    networks:
      - ccri_net

  ccrimongo7:
    container_name: ccrimongo7
    image: mongo:3.6.4
    networks:
      - ccri_net

  ccrimessaging:
    container_name: ccrimessaging
    image: thorlogic/ccri-messaging
    environment:
      - server.base.epr=http://ccrifhir:8186/ccri-fhir/STU3
      - server.base.edms=http://ccridocument2:8181/ccri-document/STU3
      - camel.route.edms=fhir://create/resource?inBody=resourceAsString&serverUrl=http://ccridocument2:8181/ccri-document/STU3&fhirVersion=DSTU3
      - camel.route.tkw=http4://192.168.128.36?throwExceptionOnFailure=true&bridgeEndpoint=true
      - ccri.epr.server.base=http://ccrifhir:8186/ccri-fhir/STU3
      - jolokia.username=HSFAdmin
      - jolokia.password=h5fadm!n
      - ccri.software.version=4.0.0
      - ccri.software.name=CCRI-Messaging
      - ccri.server=Care Connect API (unsecured)
      - server.base=https://${FHIR_SERVER_BASE_HOST}/ccri-messaging/STU3
      - ccri.guide=https://nhsconnect.github.io/CareConnectAPI/
    depends_on:
      - ccrifhir
      - ccridocument2
    ports:
      - 8112:8182
    volumes:
      - gateway-log-volume:/usr/local/tomcat/logs
    networks:
      - ccri_net

  ccridocument2:
    container_name: ccridocument2
    image: thorlogic/document-repository:latest
    depends_on:
      - ccrimongo7
    links:
      - ccrimongo7
    environment:
      - server.servlet.context-path=/ccri-document
      - server.context-path=/ccri-document
      - ccri.server.base=${FHIR_SERVER_BASE_PROTOCOL}://${FHIR_SERVER_BASE_HOST}/ccri/camel/ccri-document/STU3
      - fhir.resource.serverBase=${FHIR_SERVER_BASE_PROTOCOL}://${FHIR_SERVER_BASE_HOST}/ccri/camel/ccri-document/STU3
      - fhir.resource.serverName=Care Connect RI FHIR Server
      - fhir.resource.serverVersion=3.5.1-SNAPSHOT
      - spring.data.mongodb.uri=mongodb://ccrimongo7:27017/careconnect-nosql
      - spring.data.mongodb.database=careconnect-nosql
      - jolokia.username=HSFAdmin
      - jolokia.password=h5fadm!n
    ports:
      - 8113:8181
    volumes:
      - mongo-log-volume:/usr/local/tomcat/logs
    networks:
      - ccri_net



networks:
  ccri_net:
    driver: bridge
    ipam:
      driver: default

