version: '3'
services:
  elk:
    image: sebp/elk:562
    volumes:
      - ./elk/logstash/conf/20-filter.conf:/etc/logstash/conf.d/20-filter.conf:ro
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    networks:
      - elknet

  filebeat:
    image: docker.elastic.co/beats/filebeat:5.6.2
    volumes:
      - tomcat-log-volume:/var/log/tomcat:ro
      - gateway-log-volume:/var/log/gateway:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./elk/certs/logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt:ro
    depends_on:
      - elk
    links:
      - elk
    networks:
      - elknet

  nginx:
    image: nginx
    depends_on:
      - elk
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 20001:20001
    networks:
      - elknet

volumes:
  tomcat-log-volume:
  gateway-log-volume:

networks:
  elknet:
    driver: bridge
