FROM tomcat:8.0.46-jre8

RUN rm -rf /usr/local/tomcat/webapps/*;

RUN  mkdir /usr/local/tomcat/webapps/ROOT;

ADD index.jsp /usr/local/tomcat/webapps/ROOT/index.jsp
ADD logging.properties /usr/local/tomcat/conf/logging.properties
ADD server.xml /usr/local/tomcat/conf/server.xml

# ADD hawtio.war /usr/local/tomcat/webapps/

ADD target/careconnect-gateway.war /usr/local/tomcat/webapps/careconnect-ri.war

# See CareConnectAPI for details on pulling and running docker images https://care-connect-api.netlify.com/ccri_docker.html
EXPOSE 80

CMD ["catalina.sh", "run"]

