

INSERT INTO CodeSystem (CODESYSTEM_ID,CODE_SYSTEM_URI,CODESYSTEM_NAME)
VALUES(937,'http://hl7.org/fhir/ValueSet/encounter-participant-type','ParticipantType');

INSERT INTO Concept (CODE,DISPLAY,CODESYSTEM_ID)
VALUES('PPRF','primary performer',937);
INSERT INTO Concept (CODE,DISPLAY,CODESYSTEM_ID)
VALUES('ADM','admitter',937);
INSERT INTO Concept (CODE,DISPLAY,CODESYSTEM_ID)
VALUES('ATND','attender',937);
INSERT INTO Concept (CODE,DISPLAY,CODESYSTEM_ID)
VALUES('CALLBCK','callback contact',937);
INSERT INTO Concept (CODE,DISPLAY,CODESYSTEM_ID)
VALUES('CON','consultant',937);
INSERT INTO Concept (CODE,DISPLAY,CODESYSTEM_ID)
VALUES('DIS','discharger',937);
INSERT INTO Concept (CODE,DISPLAY,CODESYSTEM_ID)
VALUES('ESC','escort',937);
INSERT INTO Concept (CODE,DISPLAY,CODESYSTEM_ID)
VALUES('REF','referrer',937);
INSERT INTO Concept (CODE,DISPLAY,CODESYSTEM_ID)
VALUES('SPRF','secondary performer',937);
INSERT INTO Concept (CODE,DISPLAY,CODESYSTEM_ID)
VALUES('PART','Participant',937);
INSERT INTO Concept (CODE,DISPLAY,CODESYSTEM_ID)
VALUES('translator','translator',937);
INSERT INTO Concept (CODE,DISPLAY,CODESYSTEM_ID)
VALUES('emergency','emergency',937);