FROM openjdk:8-jdk-alpine
VOLUME /tmp

ENV JAVA_OPTS="-Xms128m -Xmx512m"

# ADD google3eacf3dd7222ac95.html /usr/local/tomcat/webapps/ROOT/google3eacf3dd7222ac95.html
# ADD robots.txt /usr/local/tomcat/webapps/ROOT/robots.txt


ADD target/ccri-fhir.jar ccri-fhir.jar


ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/ccri-fhir.jar"]


