
INSERT INTO CodeSystem (CODESYSTEM_ID,CODE_SYSTEM_URI,CODESYSTEM_NAME)
VALUES (950,'http://hl7.org/fhir/v3-ActEncounterCode',NULL);

INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('AMB','ambulatory',950);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('EMER','emergency',950);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('FLD','field',950);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('HH','home health',950);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('IMP','inpatient encounter',950);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('ACUTE','	inpatient acute',950);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('NONAC','inpatient non-acute',950);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('PRENC','pre-admission',950);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('SS','short stay',950);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('VR','virtual',950);
