
INSERT INTO CodeSystem (CODESYSTEM_ID,CODE_SYSTEM_URI,CODESYSTEM_NAME)
VALUES (952,'https://fhir.nhs.uk/STU3/CodeSystem/DCH-ChildHealthEncounterType-1',NULL);

INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('001','Birth Discharge	For use with the Discharge Details Event message only.',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('002','Maternity Discharge	For use with the Discharge Details Event message only.',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('003','Birth',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('004','Post Birth Review',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('005','Community Midwife Discharge',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('006','Newborn Infant Physical Examination',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('007','Newborn Hearing Screening',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('008','Newborn Blood Spot Screening',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('009','6-8 Week GP Led Review',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0010','BCG immunisation',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0011','8 week immunisations',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0012','12 week immunisations',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0013','16 week immunisations',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0014','1 Year immunisations',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0015','Pre-school immunisations',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0016','HPV immunisations',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0017','Teenage booster immunisations',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0018','Influenza immunisations',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0019','2-2 ½ Year Early Years Progress',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0020','2-2 ½ Year Heath Visitor Review',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0021','1 Year Health Review',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0022','6-8 Week Health Visitor review',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0023','New Baby Health Visitor Review',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0024','School Entry Review',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0025','National Child Measurement Programme',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0026','Ad-hoc Health Review',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0027','Ad-hoc Immunisation',952);
INSERT INTO Concept(CODE,DISPLAY,CODESYSTEM_ID) VALUES ('0028','GP Appointment',952);
