
node {

    def app

    currentBuild.result = "SUCCESS"


    stage('Checkout') {

          checkout scm
       }



    stage('Build Docker') {

            app = docker.build("ccri-fhirserver/dockerfile")
    }

    stage('Tests') {
         app.inside {
             sh 'echo "Tests Passed"'
         }
    }

    stage('Push Image') {

          docker.withRegistry('https://registry.hub.docker.com/','docker-hub-credentials') {
            app.push("latest")
            app.push("${env.BUILD_NUMBER}")
          }
    }

}

