
node {

    def app

    currentBuild.result = "SUCCESS"


    stage('Checkout') {

          checkout scm
       }



    stage('Build Docker') {

            app = docker.build("ccri")
    }


    stage('Push Image') {

          docker.withRegistry('https://registry.hub.docker.com','docker-hub-credentials') {
            app.push("latest")
            app.push("${env.BUILD_NUMBER}")
          }
    }

}

