
INSERT INTO System (SYSTEM_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,SYSTEM_URI,SYSTEM_NAME) VALUES (1,NULL,NULL,NULL,NULL,'https://fhir.nhs.uk/Id/nhs-number','NHS Number');
INSERT INTO System (SYSTEM_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,SYSTEM_URI,SYSTEM_NAME) VALUES (2,NULL,NULL,NULL,NULL,'https://fhir.nhs.uk/Id/ods-site-code','NHS Site Code');
INSERT INTO System (SYSTEM_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,SYSTEM_URI,SYSTEM_NAME) VALUES (3,NULL,NULL,NULL,NULL,'https://fhir.nhs.uk/Id/ods-organization-code','NHS Organisation Code');
INSERT INTO System (SYSTEM_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,SYSTEM_URI,SYSTEM_NAME) VALUES (5,NULL,NULL,NULL,NULL,'https://fhir.nhs.uk/Id/sds-user-id','NHS Practitioner ODS/SDS Code');
INSERT INTO System (SYSTEM_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,SYSTEM_URI,SYSTEM_NAME) VALUES (6,NULL,NULL,NULL,NULL,'phone','Phone');
INSERT INTO System (SYSTEM_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,SYSTEM_URI,SYSTEM_NAME) VALUES (7,NULL,NULL,NULL,NULL,'fax','Fax');
INSERT INTO System (SYSTEM_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,SYSTEM_URI,SYSTEM_NAME) VALUES (8,NULL,NULL,NULL,NULL,'email','Email');
INSERT INTO System (SYSTEM_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,SYSTEM_URI,SYSTEM_NAME) VALUES (9,NULL,NULL,NULL,NULL,'pager','Pager');
INSERT INTO System (SYSTEM_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,SYSTEM_URI,SYSTEM_NAME) VALUES (10,NULL,NULL,NULL,NULL,'url','Url');
INSERT INTO System (SYSTEM_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,SYSTEM_URI,SYSTEM_NAME) VALUES (11,NULL,NULL,NULL,NULL,'sms','sms');
INSERT INTO System (SYSTEM_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,SYSTEM_URI,SYSTEM_NAME) VALUES (12,NULL,NULL,NULL,NULL,'other','Other');
INSERT INTO System (SYSTEM_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,SYSTEM_URI,SYSTEM_NAME) VALUES (1001,NULL,NULL,NULL,NULL,'https://fhir.leedsth.nhs.uk/Id/pas-number','Leeds Teaching Hospitals');

