INSERT INTO Organisation (ORGANISATION_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,active,ENT_NAME,partOf,TYPE_CONCEPT_ID)
VALUES (3,NULL,NULL,NULL,NULL,NULL,'NHS EREWASH',NULL,87);

INSERT INTO Organisation (ORGANISATION_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,active,ENT_NAME,partOf,TYPE_CONCEPT_ID)
VALUES (1,NULL,NULL,NULL,NULL,NULL,'The Moir Medical Centre',3,87);

INSERT INTO Organisation (ORGANISATION_ID,RES_DELETED,RES_CREATED,RES_MESSAGE_REF,RES_UPDATED,active,ENT_NAME,partOf,TYPE_CONCEPT_ID)
VALUES (2,NULL,NULL,NULL,NULL,NULL,'Derby Teaching Hospitals NHS Foundation Trust',NULL,87);


INSERT INTO OrganisationIdentifier(ORGANISATION_IDENTIFIER_ID,IDENTIFIER_VALUE,SYSTEM_ID,ORGANISATION_ID)
VALUES (1,'C81010', 3, 1);

INSERT INTO OrganisationIdentifier(ORGANISATION_IDENTIFIER_ID,IDENTIFIER_VALUE,SYSTEM_ID,ORGANISATION_ID)
VALUES(2,'RTG', 3, 2);

INSERT INTO OrganisationIdentifier(ORGANISATION_IDENTIFIER_ID,IDENTIFIER_VALUE,SYSTEM_ID,ORGANISATION_ID)
VALUES(3,'03X', 3, 3);

INSERT INTO OrganisationTelecom(ORGANISATION_TELECOM_ID,CONTACT_VALUE,TELECOM_USE,SYSTEM_ID,ORGANISATION_ID)
VALUES (1,'0115 9737320',1, 1, 1);

INSERT INTO OrganisationTelecom(ORGANISATION_TELECOM_ID,CONTACT_VALUE,TELECOM_USE,SYSTEM_ID,ORGANISATION_ID)
VALUES (2,'01332 340131',1, 1, 2);

INSERT INTO OrganisationAddress (ORGANISATION_ADDRESS_ID,ADDRESS_ID,ORGANISATION_ID,addressUse,addressType)
VALUES(1,2,1,1,2);

INSERT INTO OrganisationAddress (ORGANISATION_ADDRESS_ID,ADDRESS_ID,ORGANISATION_ID,addressUse,addressType)
VALUES(2,3,2,1,2);

INSERT INTO OrganisationAddress (ORGANISATION_ADDRESS_ID,ADDRESS_ID,ORGANISATION_ID,addressUse,addressType)
VALUES(3,7,3,1,2);
