FROM ubuntu:16.04

MAINTAINER Kevin Mayfield

RUN apt-get update

RUN apt-get install unzip -y
RUN apt-get install curl -y

RUN mkdir /upload
WORKDIR /upload
ADD SNOMEDRelationship.ktr /upload/
ADD SNOMEDCT.ktr /upload/
ADD SNOMEDCTJob.kjb /upload/
ADD SNOMEDSubsets.ktr /upload/

RUN mkdir /usr/src/app
WORKDIR /usr/src/app
RUN curl -OL https://sourceforge.net/projects/pentaho/files/Data%20Integration/7.1/pdi-ce-7.1.0.0-12.zip
RUN unzip pdi-ce-7.1.0.0-12.zip
WORKDIR /usr/src/app/data-integration

ADD mysql-connector-java-5.1.44-bin.jar /usr/src/app/data-integration/lib/

EXPOSE 8181

CMD ["sh", "kettle.sh -file=../SNOMEDCTJob.kjb"]



