/*
-- Query: SELECT * FROM careconnect.ValueSet
LIMIT 0, 1000

-- Date: 2017-09-08 18:14
*/
INSERT INTO `ValueSet` (`VALUESET_ID`,`RES_DELETED`,`RES_CREATED`,`RES_MESSAGE_REF`,`RES_UPDATED`,`createdDate`,`description`,`CODESYSTEM_URL`,`name`,`status`,`VALUESET_STRID`,`title`,`modifiedDate`,`url`,`CODESYSTEM_PID`) VALUES (1,NULL,'2017-09-08 15:57:20',NULL,NULL,NULL,'NHS number verification status.  This valueset is comprised of codes from NHS Data Dictionary: NHS Number Status Indicator Code.',NULL,'Care Connect NHS Number Verification Status',1,'ValueSet/CareConnect-NHSNumberVerificationStatus-1',NULL,NULL,'https://fhir-test.hl7.org.uk/ValueSet/CareConnect-NHSNumberVerificationStatus-1',1);
INSERT INTO `ValueSet` (`VALUESET_ID`,`RES_DELETED`,`RES_CREATED`,`RES_MESSAGE_REF`,`RES_UPDATED`,`createdDate`,`description`,`CODESYSTEM_URL`,`name`,`status`,`VALUESET_STRID`,`title`,`modifiedDate`,`url`,`CODESYSTEM_PID`) VALUES (2,NULL,'2017-09-08 16:29:47',NULL,NULL,NULL,'The vocabulary describes the ethnic category which the patient regards as their own, designed to be used with later versions of PDS. It is an extension of the ETHNIC CATEGORY CODE described in the NHS Data Model and Dictionary for England.',NULL,'Care Connect Ethnic Category',1,'ValueSet/CareConnect-EthnicCategory-1',NULL,NULL,'https://fhir.hl7.org.uk/ValueSet/CareConnect-EthnicCategory-1',2);
INSERT INTO `ValueSet` (`VALUESET_ID`,`RES_DELETED`,`RES_CREATED`,`RES_MESSAGE_REF`,`RES_UPDATED`,`createdDate`,`description`,`CODESYSTEM_URL`,`name`,`status`,`VALUESET_STRID`,`title`,`modifiedDate`,`url`,`CODESYSTEM_PID`) VALUES (3,NULL,'2017-09-08 18:03:36',NULL,NULL,NULL,' * * * No description supplied * * *  Open Issue: The specific meanings of these codes      can vary somewhat by jurisdiction and implementation so caution should be used when determining      equivalency.',NULL,'v3 Code System MaritalStatus',1,'ValueSet/v3-MaritalStatus',NULL,NULL,'http://hl7.org/fhir/ValueSet/v3-MaritalStatus',3);
