INSERT INTO PractitionerTelecom(CONTACT_VALUE,TELECOM_USE,SYSTEM_ID,PRACTITIONER_ID)
VALUES ('abhatia@nhs.skynet',1, 2, 1);
INSERT INTO PractitionerTelecom(CONTACT_VALUE,TELECOM_USE,SYSTEM_ID,PRACTITIONER_ID)
VALUES ('karen.swamp@nhs.skynet',1, 2, 2);
INSERT INTO PractitionerTelecom(CONTACT_VALUE,TELECOM_USE,SYSTEM_ID,PRACTITIONER_ID)
VALUES('ripley.amber@nhs.skynet',1, 2, 3);

