delete from ConditionCategory;
delete from Condition_;

delete from `careconnect`.`ProcedurePerformer`;
delete from `careconnect`.`Procedure_`;

update Concept set RES_DELETED =  STR_TO_DATE('14-11-2017', '%d-%m-%Y') WHERE CONCEPT_ID = 16703  ;
update Concept set RES_DELETED = STR_TO_DATE('14-11-2017', '%d-%m-%Y')  WHERE CONCEPT_ID = 16702  ;
update Concept set RES_UPDATED = STR_TO_DATE('14-11-2017', '%d-%m-%Y'),`CODE`='encounter-diagnosis', DISPLAY='Encounter Diagnosis'  WHERE CONCEPT_ID = 16701 ;
update Concept set RES_UPDATED = STR_TO_DATE('14-11-2017', '%d-%m-%Y'),`CODE`='problem-list-item', DISPLAY='Problem List Item' WHERE CONCEPT_ID = 16700 ;

INSERT INTO Condition_ (`CONDITION_ID`,`CODE_ID`,`ENCOUNTER_ID`,`EPISODE_ID`,`PATIENT_ID`,`onsetDateTime`,`CLINICAL_STATUS_CONCEPT_ID`,`CODE_CONCEPT_ID`,`assertedDateTime`,`ASSERTER_PRACTITIONER_ID`,`verificationStatus`)
VALUES (1,null,null,null,4,'2010-10-09 09:00:00',null,null,'2010-10-09 09:00:00',200001,2);

INSERT INTO Condition_ (`CONDITION_ID`,`CODE_ID`,`ENCOUNTER_ID`,`EPISODE_ID`,`PATIENT_ID`,`onsetDateTime`,`CLINICAL_STATUS_CONCEPT_ID`,`CODE_CONCEPT_ID`,`assertedDateTime`,`ASSERTER_PRACTITIONER_ID`,`verificationStatus`)
VALUES (2,null,null,null,1,'2010-10-09 09:00:00',null,null,'2010-10-09 09:00:00',1,2);

INSERT INTO ConditionCategory (`CONDITION_CATEGORY_ID`,`CONDITION_ID`,`CATEGORY_CONCEPT_ID`)
VALUES(1,1,709);

INSERT INTO ConditionCategory (`CONDITION_CATEGORY_ID`,`CONDITION_ID`,`CATEGORY_CONCEPT_ID`)
VALUES(2,2,709);

INSERT INTO `Procedure_` (`PROCEDURE_ID`,`CODE_ID`,`ENCOUNTER_ID`,`PATIENT_ID`,`performedDate`,`notDone`,`status`,`BASED_ON_REFERRAL_REQUEST_ID`,`BODY_SITE_CONCEPT_ID`,`CATEGORY_CONCEPT_ID`,`EPISODE_OF_CARE_ID`,`PROCEDURE_LOCATION_ID`,`NOT_DONE_REASON_CONCEPT_ID`,`OUTCOME_CONCEPT_ID`,`PART_OF_PROCEDURE_ID`,`REASON_CONCEPT_ID`,`REASON_CONDITION`,`REASON_OBSERVATION`)
VALUES (1,null,null,4,'2010-10-20 20:56:00', null,4,null,null,null,1,null,null,null,null,null,1,null);

INSERT INTO `Procedure_` (`PROCEDURE_ID`,`CODE_ID`,`ENCOUNTER_ID`,`PATIENT_ID`,`performedDate`,`notDone`,`status`,`BASED_ON_REFERRAL_REQUEST_ID`,`BODY_SITE_CONCEPT_ID`,`CATEGORY_CONCEPT_ID`,`EPISODE_OF_CARE_ID`,`PROCEDURE_LOCATION_ID`,`NOT_DONE_REASON_CONCEPT_ID`,`OUTCOME_CONCEPT_ID`,`PART_OF_PROCEDURE_ID`,`REASON_CONCEPT_ID`,`REASON_CONDITION`,`REASON_OBSERVATION`)
VALUES (2,null,null,1,'2017-03-22T09:30:10', null,4,null,null,null,null,null,null,null,null,null,2,null);


INSERT INTO `ProcedurePerformer` (`PROCEDURE_PERFORMER_ID`,`ACTOR_ORGNANISATION`,`ACTOR_PRACTITIONER`,`ON_BEHALF_OF_ORGANISATION`,`PROCEDURE_ID`,`ROLE_CONCEPT_ID`)
VALUES (1,null,200001,null,1,null);
INSERT INTO `ProcedurePerformer` (`PROCEDURE_PERFORMER_ID`,`ACTOR_ORGNANISATION`,`ACTOR_PRACTITIONER`,`ON_BEHALF_OF_ORGANISATION`,`PROCEDURE_ID`,`ROLE_CONCEPT_ID`)
VALUES (2,200001,null,null,2,null);